import 'package:csv/csv.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../core/constants/app_constants.dart';
import '../models/activity.dart';

/// 遊びリポジトリのインターフェース
abstract class ActivityRepository {
  Future<List<Activity>> getAllActivities();
  Future<Activity?> getActivityById(String id);
}

/// Firebase / CSV / InMemory 統合 ActivityRepository 実装
class FirestoreActivityRepository implements ActivityRepository {
  List<Activity>? _cachedActivities;
  // 初期マスターシードデータ（50種類のバリエーション豊かな構造化遊びデータ）
  static final List<Activity> _seedActivities = [
    // 1
    Activity(
      id: 'act_001',
      title: '影踏みオニごっこ',
      description: '相手の影を足で踏むシンプルで白熱する鬼ごっこ！日当たりの良い公園や広場で思い切り走れます。',
      minAge: 4,
      maxAge: 10,
      minParticipants: 2,
      maxParticipants: 6,
      durationMinutes: 15,
      locationTypes: [LocationType.park, LocationType.spacious],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.agility, AbilityType.stamina, AbilityType.thinking],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['周りの遊具や他の人にぶつからない開けた場所で行ってください。', '水分補給をこまめに行いましょう。'],
      steps: ['じゃんけんで最初の鬼を決めます。', '鬼は「30秒」数えてから逃げる人の影を踏みに行きます。', '自分の影を踏まれた人は新しい鬼になります。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「影がどんどん逃げるよ〜！追いつけるかな？」', '「方向転換が素早くてかっこいい！」', '「太陽の向きをよく見て影の伸び方を工夫できたね！」'],
      imageUrl: 'assets/images/activity_tag_chase.jpg',
    ),

    // 2
    Activity(
      id: 'act_002',
      title: '新聞紙ビリビリ・キャッチ',
      description: '部屋の中で安全にできる運動！破いた新聞紙をひらひら落として足や手でキャッチ！',
      minAge: 3,
      maxAge: 8,
      minParticipants: 1,
      maxParticipants: 4,
      durationMinutes: 20,
      locationTypes: [LocationType.indoor, LocationType.yard],
      toolsRequired: ['新聞紙/紙'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.agility, AbilityType.rhythm, AbilityType.balance],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['床に散らばった新聞紙で滑らないよう、靴下を脱いで裸足で行うのが安全です。'],
      steps: ['新聞紙を様々な大きさに破ります。', '保護者が高い位置から新聞紙をひらひら落とします。', '子どもは地面に落ちる前に手や足でキャッチします！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「ひらひら揺れる新聞紙をしっかり目で見えてたね！」', '「ナイスキャッチ！キャッチする瞬間のお顔が真剣で素敵！」', '「次はもっと高いところから落とすよ〜準備はいい？」'],
      imageUrl: 'assets/images/activity_newspaper_catch.jpg',
    ),

    // 3
    Activity(
      id: 'act_003',
      title: 'あにまるマーチ（動物まねっこレース）',
      description: 'うさぎやライオン、カエルになりきって室内や庭を歩きます。全身の体幹と柔軟性を育みます。',
      minAge: 2,
      maxAge: 6,
      minParticipants: 1,
      maxParticipants: 5,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor, LocationType.yard],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.balance, AbilityType.flexibility, AbilityType.rhythm],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['家具の角に頭をぶつけないようスペースを確保しましょう。'],
      steps: ['カードやお題で動物を指名します（例: 「うさぎ」「クマ」）。', 'うさぎは両足ジャンプ、クマは四つん足でしっかり歩きます。', 'ゴールまで動物の鳴き真似もしながら進みます！'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「うわ〜！うさぎさんのジャンプ、とっても高く跳べてるね！」', '「クマさんの歩き方、体幹がしっかりブレなくて力強い！」', '「動物になりきる表現力が素晴らしいね！」'],
      imageUrl: 'https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=600&q=80',
    ),

    // 4
    Activity(
      id: 'act_004',
      title: '風船ポンポンリレー',
      description: '風船を床に落とさないように手やうちわでパッティングしながら目標を回って戻るリレー！',
      minAge: 4,
      maxAge: 9,
      minParticipants: 2,
      maxParticipants: 6,
      durationMinutes: 15,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['ボール'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.agility, AbilityType.cooperation, AbilityType.rhythm],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['割れた風船を誤飲しないよう大人がしっかり見守ってください。'],
      steps: ['ふくらませた風船を1人1個またはペアで1個持ちます。', '落とさないように下から上にポンポン叩きながら歩いて進みます。', '部屋の反対側のコーンを回って無事にスタートへ戻りましょう。'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「力かげんが優しくて風船のコントロールがすごく上手！」', '「最後まであきらめずに風船を追いかけられたね！」', '「息を合わせて協力できて最高のチームだね！」'],
      imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=600&q=80',
    ),

    // 5
    Activity(
      id: 'act_005',
      title: 'だるまさんが転んだ（アクション進化版）',
      description: '「だるまさんが転んだ！」のフレーズの後、ポーズを指定（例: 片足立ちポーズ、フラミンゴ）。バランス感覚を鍛えます。',
      minAge: 4,
      maxAge: 12,
      minParticipants: 3,
      maxParticipants: 8,
      durationMinutes: 20,
      locationTypes: [LocationType.park, LocationType.spacious, LocationType.yard],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.balance, AbilityType.agility, AbilityType.thinking],
      isRainOk: false,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['止まるときに転倒しないよう、平らな場所で行いましょう。'],
      steps: ['鬼が木や壁を背にして「だるまさんが転んだ」と言います。', '言っている間に他の人は近づきます。', '鬼が振り向いた時、指定されたポーズ（片足ピタッ）で止まります！'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「ピタッと静止する集中力がピカイチ！」', '「フラミンゴのポーズ、バランス感覚がすごいね！」', '「鬼の動きをしっかり観察して前に進めたね！」'],
      imageUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=600&q=80',
    ),

    // 6
    Activity(
      id: 'act_006',
      title: 'けんけんぱサーキット',
      description: '地面に丸を描いたり、輪っかを置いてけんけんぱ！途中にジャンプゾーンやダッシュゾーンを入れて全身運動。',
      minAge: 5,
      maxAge: 10,
      minParticipants: 1,
      maxParticipants: 4,
      durationMinutes: 15,
      locationTypes: [LocationType.park, LocationType.yard, LocationType.spacious],
      toolsRequired: ['マーカー/コーン'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.stamina, AbilityType.rhythm, AbilityType.balance],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 4,
      safetyTips: ['着地時に足首をひねらないよう注意しましょう。'],
      steps: ['地面に「片足」「両足」のゾーンを交互に設定します。', 'リズムよく「ケン・ケン・パ！」と声を出しながら跳んでいきます。', 'タイムアタックに挑戦！'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「ケン・ケン・パのリズム感がとってもいいね！」', '「両足で着地するときもしっかり安定してる！」', '「タイム更新おめでとう！諦めずにダッシュできたね！」'],
      imageUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=600&q=80',
    ),

    // 7
    Activity(
      id: 'act_007',
      title: 'リビング島渡り探検',
      description: 'クッションや座布団を海に浮かぶ「島」に見立て、床（マグマ）に落ちないよう渡っていく室内スリルゲーム！',
      minAge: 3,
      maxAge: 7,
      minParticipants: 1,
      maxParticipants: 3,
      durationMinutes: 15,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['タオル'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.balance, AbilityType.thinking, AbilityType.agility],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['クッションが滑らないよう滑り止めマットを敷くか、大人が固定してください。'],
      steps: ['クッションを少しずつ離して置きます。', 'スタートからゴールまで、床に足をつかずに渡りきります。', '島の間隔を少しずつ広げて難易度アップ！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「あぶない！ナイスバランスで耐えたね！」', '「次の島へ思い切って一歩踏み出せたのが素晴らしい！」'],
    ),

    // 8
    Activity(
      id: 'act_008',
      title: 'タオル引っ張り合い（室内綱引き）',
      description: 'フェイスタオルやバスタオルを両端から引っ張り合う全身力比べ！体幹と握力を鍛えます。',
      minAge: 4,
      maxAge: 10,
      minParticipants: 2,
      maxParticipants: 4,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor, LocationType.yard],
      toolsRequired: ['タオル'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.stamina, AbilityType.balance, AbilityType.cooperation],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 4,
      safetyTips: ['タオルを急に手離すと転倒するため、離す時は声を掛け合いましょう。'],
      steps: ['タオルの端をしっかり握ります。', '中央の境界線を超えて相手を引き寄せたら勝ち！', '膝を曲げて低い姿勢をとるのがコツです。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「踏ん張る脚の力が強くなったね！」', '「低い姿勢で耐えててかっこいい！」'],
    ),

    // 9
    Activity(
      id: 'act_009',
      title: '落ち葉・どんぐりトレジャーハンター',
      description: '「赤くて大きな葉っぱ」「丸いどんぐり」などお題に合う自然の宝物を探して公園をのんびり探索。',
      minAge: 2,
      maxAge: 7,
      minParticipants: 1,
      maxParticipants: 4,
      durationMinutes: 30,
      locationTypes: [LocationType.park, LocationType.spacious],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.thinking, AbilityType.flexibility, AbilityType.stamina],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['口の中に落ち葉や木の実を入れないよう見守ってください。'],
      steps: ['保護者が「宝物カード（お題）」を出します。', '公園の中を探検しながらお題にぴったりな落ち葉や枝を探します。', '見つけたら「発見！」と宣言して宝箱（袋）にしまおう。'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「きれいな色の葉っぱをよく観察できたね！」', '「宝物を発見した時の笑顔が最高！」'],
      seasons: [Season.autumn], // 秋限定！
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    ),

    // 10
    Activity(
      id: 'act_010',
      title: '紙コップ倒しボウリング',
      description: 'ピラミッド状に積んだ紙コップに柔らかいボールを転がして一気に倒す爽快ゲーム！',
      minAge: 3,
      maxAge: 8,
      minParticipants: 1,
      maxParticipants: 4,
      durationMinutes: 15,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['ボール', '新聞紙/紙'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.agility, AbilityType.thinking, AbilityType.rhythm],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['硬いボールは家具を傷つけるためゴムボールや布ボールを使用してください。'],
      steps: ['紙コップを10個、ピラミッド状に並べます。', '2〜3メートル離れた場所からボールを転がします。', '何個倒せたかスコアを数えて競い合おう！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「真ん中をしっかり狙ってコントロールバッチリ！」', '「倒れる音と勢いが最高だね！」'],
    ),

    // 11
    Activity(
      id: 'act_011',
      title: 'カエル跳びジャンプリレー',
      description: 'しゃがんだ姿勢から両手・両足を使ってダイナミックにジャンプ！股関節と下半身の爆発力を高めます。',
      minAge: 5,
      maxAge: 11,
      minParticipants: 1,
      maxParticipants: 6,
      durationMinutes: 15,
      locationTypes: [LocationType.park, LocationType.spacious],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.stamina, AbilityType.agility, AbilityType.balance],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 4,
      safetyTips: ['手をつく場所に石や危険物がないか事前に確認してください。'],
      steps: ['両手を地面につき、しゃがみ込みます。', '「ゲコッ！」と声を出しながら前に大きくジャンプ！', 'ゴールまで何回跳べるか記録に挑戦。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「足のバネが効いてて遠くまで跳べたね！」', '「カエルになりきって全力で進む姿がカッコいい！」'],
    ),

    // 12
    Activity(
      id: 'act_012',
      title: 'お部屋サーキット（障害物競走）',
      description: 'クッションを跳び越え、テーブルの下を潜り抜け、壁にタッチして戻ってくる屋内サーキット！',
      minAge: 4,
      maxAge: 9,
      minParticipants: 1,
      maxParticipants: 3,
      durationMinutes: 20,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.agility, AbilityType.flexibility, AbilityType.stamina],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 4,
      safetyTips: ['家具の角をクッションで保護し、走って滑らないよう注意してください。'],
      steps: ['コース（またぐ・くぐる・タッチする）を決めます。', 'よーいドン！で障害物をクリアしていきます。', '安全第一でタイム計測して楽しみます。'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「くぐる動作がすごくスムーズで速い！」', '「コースを間違えずに全部クリアできたね！」'],
    ),

    // 13
    Activity(
      id: 'act_013',
      title: 'ぴったり何歩？歩数当てウォーキング',
      description: '「あのベンチまで何歩で行けるかな？」と予測してから歩く、頭と足を使った散歩ゲーム。',
      minAge: 5,
      maxAge: 12,
      minParticipants: 2,
      maxParticipants: 5,
      durationMinutes: 25,
      locationTypes: [LocationType.park, LocationType.spacious],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.thinking, AbilityType.stamina, AbilityType.rhythm],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['車通りがない歩道や公園内の遊歩道で行ってください。'],
      steps: ['目印の場所を決め、「20歩！」などと歩数を予想します。', '一歩ずつ大きな声で「いち、に、さん…」と数えながら歩きます。', '一番予想に近かった人が勝ち！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「予想がぴったり近くて驚いたよ！」', '「歩幅を調整してコントロールするのが上手だね！」'],
    ),

    // 14
    Activity(
      id: 'act_014',
      title: 'しっぽ取り鬼ごっこ',
      description: 'ズボンの後ろにタオルを挟み、お互いに「しっぽ」を奪い合う大人気のアクティブ運動！',
      minAge: 3,
      maxAge: 10,
      minParticipants: 2,
      maxParticipants: 8,
      durationMinutes: 15,
      locationTypes: [LocationType.park, LocationType.yard, LocationType.spacious],
      toolsRequired: ['タオル'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.agility, AbilityType.stamina, AbilityType.thinking],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['服を強く引っ張らず、タオルだけを取るように約束しましょう。'],
      steps: ['ズボンの背中側にタオルを半分垂らして挟みます。', '合図とともに走り回り、相手のしっぽを取ります。', '最後まで自分のしっぽを守り切った人の勝ち！'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「背後を守る動きのキレが素晴らしい！」', '「すばやい手が伸びてしっぽゲットだね！」'],
    ),

    // 15
    Activity(
      id: 'act_015',
      title: '風船バレーボール対戦',
      description: 'リビングのテーブルやソファをネットに見立て、ふわふわ風船でラリーを続ける平和なバレー！',
      minAge: 4,
      maxAge: 12,
      minParticipants: 2,
      maxParticipants: 4,
      durationMinutes: 20,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['ボール'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.cooperation, AbilityType.agility, AbilityType.rhythm],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['風船を追いかけて家具にぶつからないよう距離を意識しましょう。'],
      steps: ['部屋の中央に境界線（または低い障害物）を作ります。', '手で風船を打ち合い、ラリーを続けます。', '「10回ラリー達成！」を目指して協力プレイ。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「ナイスレシーブ！風船の下に入るのが早い！」', '「お互いに声を掛け合ってつながったね！」'],
    ),

    // 16
    Activity(
      id: 'act_016',
      title: 'まねっこダンス＆ストップ',
      description: '手拍子や音楽に合わせて思い思いに踊り、音が止まった瞬間にピタッと静止する表現運動！',
      minAge: 2,
      maxAge: 6,
      minParticipants: 1,
      maxParticipants: 6,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.rhythm, AbilityType.balance, AbilityType.flexibility],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['周りに物がない部屋の中央で行ってください。'],
      steps: ['保護者の歌や手拍子に合わせてノリノリでダンス！', '「ストップ！」の合図でどんなポーズでもいいので止まります。', '面白ポーズでみんなで大笑い！'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「ダンスのリズム感が最高にかわいい！」', '「ピタッとストップした時の変顔ポーズが最高！」'],
    ),

    // 17
    Activity(
      id: 'act_017',
      title: 'ボールキャッチ＆カウント',
      description: '二人で向き合い、ボールを投げ合ってノーバウンドで連続何回キャッチできるか記録に挑戦。',
      minAge: 4,
      maxAge: 10,
      minParticipants: 2,
      maxParticipants: 4,
      durationMinutes: 15,
      locationTypes: [LocationType.park, LocationType.yard, LocationType.spacious],
      toolsRequired: ['ボール'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.agility, AbilityType.cooperation, AbilityType.rhythm],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['柔らかいボールを使用し、胸の高さに優しく投げましょう。'],
      steps: ['2mほど離れて向かい合います。', '「いち！に！さん！」と声を出してパス交換。', '落とさずに最高記録を目指そう。'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「ボールをしっかり最後まで目で見れてるよ！」', '「優しいパスだから捕りやすいね、ありがとう！」'],
    ),

    // 18
    Activity(
      id: 'act_018',
      title: '縄跳びニョロニョロヘビジャンプ',
      description: '地面に置いた縄跳びを大人がニョロニョロ揺らし、踏まないようにジャンプして跳び越える！',
      minAge: 3,
      maxAge: 8,
      minParticipants: 2,
      maxParticipants: 5,
      durationMinutes: 15,
      locationTypes: [LocationType.park, LocationType.yard],
      toolsRequired: ['縄跳び'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.agility, AbilityType.rhythm, AbilityType.balance],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['縄跳びの柄（持ち手）が体に当たらないよう気をつけて持ちましょう。'],
      steps: ['大人が縄跳びの端を持ち、地面で左右に波立たせます。', '子どもは蛇に触れないよう「トビッ！」と跳び越えます。', '波を大きくしたり速くしたり変化をつけます。'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「ヘビの動きのタイミングをよく見極められたね！」', '「両足そろえて軽やかにジャンプできたね！」'],
    ),

    // 19
    Activity(
      id: 'act_019',
      title: 'フラミンゴ片足立ちグラグラ対決',
      description: '片足を上げてどちらが長く立っていられるか競う！体幹の強さと集中力を養います。',
      minAge: 4,
      maxAge: 12,
      minParticipants: 2,
      maxParticipants: 6,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor, LocationType.yard, LocationType.park],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.balance, AbilityType.thinking, AbilityType.stamina],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['よろけた際に周囲の壁やテーブルにぶつからない場所で行ってください。'],
      steps: ['両手をお腹の前で組むか羽のように広げます。', '片足を上げて「よーいスタート！」。', '目線を遠くの一点に集中させるのが長持ちの秘密。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「軸足がブレなくて軸がしっかり通ってる！」', '「グラグラしても持ちこたえたのがすごい！」'],
    ),

    // 20
    Activity(
      id: 'act_020',
      title: '親子ストレッチトレイン',
      description: '前後に並んで前の人のポーズ（開脚・前屈・背伸び）を真似して体をほぐすリラックス運動。',
      minAge: 2,
      maxAge: 6,
      minParticipants: 2,
      maxParticipants: 4,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.flexibility, AbilityType.cooperation, AbilityType.rhythm],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['無理に体を倒しすぎず、気持ちいい範囲で伸ばしましょう。'],
      steps: ['シュッシュッポッポと汽車になって部屋を一周。', '「駅に到着！」で停車し、体をグーンと伸ばすストレッチ。', '交代して子どもが車長（ポーズの指示役）になります。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「背中がとっても柔らかく伸びてるね！」', '「お互い真似っこして体がポカポカしてきたね！」'],
    ),

    // 21
    Activity(
      id: 'act_021',
      title: '公園遊具周回タイムアタック',
      description: 'すべり台→ブランコの周り→鉄棒を順番にタッチして戻る公園全体の探検タイムレース！',
      minAge: 6,
      maxAge: 12,
      minParticipants: 1,
      maxParticipants: 4,
      durationMinutes: 20,
      locationTypes: [LocationType.park],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.stamina, AbilityType.agility, AbilityType.thinking],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 4,
      safetyTips: ['他の利用者に配慮し、すべり台やブランコの動線に割り込まないよう配慮してください。'],
      steps: ['安全な周回チェックポイントを設定します。', 'よーいドンで各遊具を安全に手でタッチ！', '前回のタイムを超えられるかチャレンジ。'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「最後まで全速力で走り抜けてすごいスタミナ！」', '「前回の記録を3秒も更新できたね！」'],
    ),

    // 22
    Activity(
      id: 'act_022',
      title: 'ペットボトル空気砲ターゲット射撃',
      description: 'ペットボトルの底を切って風船を張った手作り空気砲で、的に当てて倒す工作＆物理運動！',
      minAge: 4,
      maxAge: 9,
      minParticipants: 1,
      maxParticipants: 3,
      durationMinutes: 25,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['新聞紙/纸'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.thinking, AbilityType.agility, AbilityType.rhythm],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['切ったペットボトルの切り口で手を切らないようテープで保護してください。'],
      steps: ['空気砲の風船を引っ張ってパチンと放ちます。', '空気の力で紙のターゲットを吹き飛ばします。', '距離を遠くしてエイム力を試そう！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「見事に命中！引く力と狙いがぴったりだったね！」', '「空気のパワーを上手にコントロールできたね！」'],
    ),

    // 23
    Activity(
      id: 'act_023',
      title: 'スリッパ飛ばしピッタリ選手権',
      description: '足先でスリッパをポーンと飛ばし、指定したエリア（目標の線）に一番近く飛ばした人が勝ち！',
      minAge: 5,
      maxAge: 12,
      minParticipants: 2,
      maxParticipants: 6,
      durationMinutes: 15,
      locationTypes: [LocationType.yard, LocationType.park],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.balance, AbilityType.thinking, AbilityType.flexibility],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['人のいる方向に飛ばさないよう、飛ばす方向を固定して安全を確保してください。'],
      steps: ['スタート線に立ち、片足にスリッパ（靴）を浅く履きます。', '足を前に振り上げてポーンと遠くへ飛ばします。', '遠さだけでなく「狙った場所に落とせるか」を楽しみます。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「足の振りとリリースのタイミングが完璧！」', '「目標のすぐ近くにピタッと落ちてすごい！」'],
    ),

    // 24
    Activity(
      id: 'act_024',
      title: '忍者のシノビ歩き（音を立てずに移動）',
      description: '足音を一切立てずに忍び足で親の背後に近づく静寂のゲーム。足指のコントロール力を高めます。',
      minAge: 3,
      maxAge: 8,
      minParticipants: 2,
      maxParticipants: 4,
      durationMinutes: 15,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.balance, AbilityType.thinking, AbilityType.flexibility],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['つま先から静かに着地し、足指をしっかり使いましょう。'],
      steps: ['親が壁を向いて背中を見せます。', '子どもは足音を「トントン」立てずに抜き足差し足で接近。', '音を立てたらスタートへ戻り、肩をタッチできたら忍者合格！'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「全然足音が聞こえなくて本物の忍者かと思った！」', '「つま先を上手に使って着地できてたね！」'],
    ),

    // 25
    Activity(
      id: 'act_025',
      title: '空中タオルキャッチダッシュ',
      description: '大人が投げてヒラヒラ落ちてくるタオルを、ダッシュして地面につく前にキャッチ！',
      minAge: 5,
      maxAge: 11,
      minParticipants: 2,
      maxParticipants: 4,
      durationMinutes: 15,
      locationTypes: [LocationType.park, LocationType.spacious],
      toolsRequired: ['タオル'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.agility, AbilityType.stamina, AbilityType.rhythm],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['地面に飛び込む際に転んでケガをしないよう芝生など柔らかい場所で行ってください。'],
      steps: ['大人が高く斜め前にタオルを放り投げます。', '子どもはスタート位置から一気にダッシュ！', '落下地点を見極めてダイブまたは素早くキャッチ！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「落下のスピードとダッシュのタイミングが最高！」', '「風の動きまで読んで動けてたね！」'],
    ),

    // 26
    Activity(
      id: 'act_026',
      title: 'フリスビーターゲットパス',
      description: 'フリスビーを回転させて親の手元やマーカーに向けて投げる！手首のスナップと距離感を鍛えます。',
      minAge: 6,
      maxAge: 12,
      minParticipants: 2,
      maxParticipants: 5,
      durationMinutes: 20,
      locationTypes: [LocationType.park, LocationType.spacious],
      toolsRequired: ['フリスビー'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.cooperation, AbilityType.rhythm, AbilityType.thinking],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['柔らかい布製またはソフトプラスチック製のフリスビーを使用しましょう。'],
      steps: ['5〜10メートル離れて向かい合います。', '手首をスナップさせて水平にフリスビーを投げます。', '相手の胸の高さへきれいに飛ばせるか挑戦。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「フリスビーがまっすぐ綺麗な軌道で飛んできたよ！」', '「手首のスナップの利かせ方が上手だね！」'],
    ),

    // 27
    Activity(
      id: 'act_027',
      title: 'たかい・たかい飛行機バランス',
      description: '大人が仰向けになり、足の裏で子どものお腹を支えて空飛ぶ飛行機ポーズ！スキンシップと体幹鍛練。',
      minAge: 2,
      maxAge: 5,
      minParticipants: 2,
      maxParticipants: 2,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.balance, AbilityType.cooperation, AbilityType.flexibility],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 4,
      safetyTips: ['手を出していつでも支えられるようにし、布団やマットの上で行ってください。'],
      steps: ['大人は仰向けになり、両膝を曲げて足裏を子どものお腹に当てます。', '子どもと両手を繋ぎながら持ち上げます。', '「ぶーん！」と飛行機になってバランスをとろう。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「お腹に力を入れてカッコいい飛行機になれたね！」', '「手を開いてバランスをとるのがうまい！」'],
    ),

    // 28
    Activity(
      id: 'act_028',
      title: '新聞紙ボール玉入れ合戦',
      description: '丸めた新聞紙ボールを部屋の中央のランドリーバスケットやダンボールに投げ入れる玉入れ！',
      minAge: 3,
      maxAge: 7,
      minParticipants: 1,
      maxParticipants: 5,
      durationMinutes: 15,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['新聞紙/紙'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.agility, AbilityType.thinking, AbilityType.rhythm],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['ボールを投げるときに他の人の顔に当たらないよう注意しましょう。'],
      steps: ['新聞紙を丸めて20個以上のボールを作ります。', 'タイマーを30秒にセット！', '時間内に何個入れられるか玉入れスタート！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「コントロールがよくてどんどん籠に入っていくね！」', '「素早くボールを拾って投げる手返しが早い！」'],
    ),

    // 29
    Activity(
      id: 'act_029',
      title: '一本橋バランス平均台歩き',
      description: 'フローリングの目地やマスキングテープの上を落っこちないように一本橋歩き。',
      minAge: 3,
      maxAge: 7,
      minParticipants: 1,
      maxParticipants: 3,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor, LocationType.park],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.balance, AbilityType.flexibility, AbilityType.thinking],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['周囲にぶつかる家具がない一本道を確保してください。'],
      steps: ['床にまっすぐ線（テープやひも）をひきます。', 'つま先とカカトをくっつけるようにして慎重に進みます。', '途中でカエルポーズなどのミッションを入れて楽しもう。'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「線から落ちずに最後まで歩ききれてすごい集中力！」', '「手を広げて上手にバランスを取れていたね！」'],
    ),

    // 30
    Activity(
      id: 'act_030',
      title: '転がるボールをキックチェイス',
      description: '大人が前に転がしたサッカーボールを走って追いかけ、止めてシュート！',
      minAge: 4,
      maxAge: 9,
      minParticipants: 2,
      maxParticipants: 4,
      durationMinutes: 20,
      locationTypes: [LocationType.park, LocationType.spacious],
      toolsRequired: ['ボール'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.stamina, AbilityType.agility, AbilityType.rhythm],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['道路へ飛び出さないよう、完全に囲まれた広場で行ってください。'],
      steps: ['大人が前方へ強めにボールを転がします。', '子どもは全力で追いかけて足でピタッとボールを止めます（トラップ）。', 'そのまま目標のゴールへキック！'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「足の裏でピタッとボールを止める技術がかっこいい！」', '「追いかけるダッシュのスピードが素晴らしい！」'],
    ),

    // 31
    Activity(
      id: 'act_031',
      title: '鏡あそびシンクロポーズ',
      description: '親と向かい合い、一方が「本物」でもう一方が「鏡」。相手の動きをリアルタイムにシンクロ真似っこ！',
      minAge: 3,
      maxAge: 8,
      minParticipants: 2,
      maxParticipants: 4,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.thinking, AbilityType.flexibility, AbilityType.cooperation],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['ゆっくりとした動作から始めましょう。'],
      steps: ['向かい合って手を合わせる距離に立ちます。', '一人がゆっくり手や足を動かし、もう一人は鏡のように完全に同じ動きをします。', '役割を交代してシンクロ度を楽しみます。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「本当の鏡を見ているみたいに動きがピッタリ！」', '「相手をじっくり観察する集中力がすごいね！」'],
    ),

    // 32
    Activity(
      id: 'act_032',
      title: '信号機ゲーム（青・赤・黄）',
      description: '「青」で猛ダッシュ、「黄」でゆっくり歩き、「赤」でピタッと停止！指示への即時反応力を養う運動。',
      minAge: 3,
      maxAge: 8,
      minParticipants: 2,
      maxParticipants: 6,
      durationMinutes: 15,
      locationTypes: [LocationType.park, LocationType.yard, LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.agility, AbilityType.thinking, AbilityType.balance],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['室内で行う場合は壁に激突しないよう距離を保ちましょう。'],
      steps: ['大人が信号機役になり掛け声をかけます。', '「青！」でダッシュ、「黄！」でスローモーション、「赤！」でストップ。', '反応速度を競って楽しみます。'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「赤の瞬間のブレーキの効き目が素晴らしい！」', '「耳でしっかり掛け声を聞けて素早く反応できたね！」'],
    ),

    // 33
    Activity(
      id: 'act_033',
      title: 'お手玉・ボールトス挑戦',
      description: '片手で投げて反対の手でキャッチしたり、2つのボールを順番に空中で投げ交わす手先のコントロール！',
      minAge: 6,
      maxAge: 12,
      minParticipants: 1,
      maxParticipants: 3,
      durationMinutes: 15,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['ボール'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.hard,
      trainableAbilities: [AbilityType.agility, AbilityType.rhythm, AbilityType.thinking],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['周りの家具にボールが当たらないスペースで行ってください。'],
      steps: ['まずは1個のボールを右手に持って左手へ投げてキャッチ。', '慣れたら2個持って交互にトス！', '連続何回成功するか挑戦。'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「手元を見ずにボールの軌道を捉えられてる！」', '「何度もチャレンジしてどんどん上手になってるね！」'],
    ),

    // 34
    Activity(
      id: 'act_034',
      title: 'クッションハイジャンプキング',
      description: '積み重ねたクッションを助走をつけて両足で力強く飛び越えるダイナミック運動！',
      minAge: 4,
      maxAge: 8,
      minParticipants: 1,
      maxParticipants: 3,
      durationMinutes: 15,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.stamina, AbilityType.agility, AbilityType.balance],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 4,
      safetyTips: ['着地地点に布団などを敷き、滑らないように配慮してください。'],
      steps: ['クッションを1段置きます。', '助走をつけて「トビッ！」と両足で跳び越えます。', '成功したら2段、3段と高さを増していきます。'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「膝をしっかり曲げて高く跳躍できたね！」', '「両足そろえた着地がバシッと決まってカッコいい！」'],
    ),

    // 35
    Activity(
      id: 'act_035',
      title: '両手両足タッチあみだくじ',
      description: '床に配置した紙に「右足」「左手」などの指示が書かれており、正しくタッチしながら進むツイスター風ゲーム！',
      minAge: 5,
      maxAge: 10,
      minParticipants: 1,
      maxParticipants: 4,
      durationMinutes: 20,
      locationTypes: [LocationType.indoor, LocationType.yard],
      toolsRequired: ['新聞紙/紙'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.flexibility, AbilityType.balance, AbilityType.thinking],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['体勢を崩したときに手をつけるよう配慮してください。'],
      steps: ['手形・足形を描いた紙を床に格子状に並べます。', '指示通りに手や足を紙の上に置いていきます。', '倒れずにゴールまでたどり着こう！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「体がぐーんと伸びて柔軟性が素晴らしい！」', '「手と足を間違えずに素早く判断できたね！」'],
    ),

    // 36
    Activity(
      id: 'act_036',
      title: 'ドッジボールターゲット当て練習',
      description: '的に見立てたダンボール箱や壁のマーカーに力いっぱいボールを当ててコントロール向上！',
      minAge: 6,
      maxAge: 12,
      minParticipants: 1,
      maxParticipants: 4,
      durationMinutes: 20,
      locationTypes: [LocationType.park, LocationType.spacious],
      toolsRequired: ['ボール', 'マーカー/コーン'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.stamina, AbilityType.agility, AbilityType.thinking],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['人にボールが当たらないよう、投げる方向の安全を確認してください。'],
      steps: ['5メートル先にターゲットをセット。', 'オーバースローで体重を乗せてボールを投げます。', '何回連続で的にヒットできるか記録更新を狙おう。'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「体重移動がしっかりできて投球に勢いがある！」', '「的のど真ん中に当たったね、ナイスピッチ！」'],
    ),

    // 37
    Activity(
      id: 'act_037',
      title: 'お布団でんぐり返し＆決めポーズ',
      description: '布団やマットの上で安全に前回り（でんぐり返し）をし、立ち上がってカッコよく決めポーズ！',
      minAge: 3,
      maxAge: 7,
      minParticipants: 1,
      maxParticipants: 3,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.balance, AbilityType.flexibility, AbilityType.rhythm],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['おへそを見るように首を丸めて回るよう指導してください。'],
      steps: ['布団の上でしゃがみ、両手をしっかりつきます。', '頭のてっぺんではなく後頭部をつけ、おへそを見ながら回転。', 'くるっと回ったら勢いよく立って「ジャキーン！」'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「おへそをしっかり見てきれいに回れたね！」', '「回ったあとの決めポーズがバッチリ決まってる！」'],
    ),

    // 38
    Activity(
      id: 'act_038',
      title: 'パパママ人間トンネルくぐり',
      description: '大人が四つん足や高いくぐる姿勢を作り、その下をハイハイや腹ばいで素早くくぐり抜ける！',
      minAge: 2,
      maxAge: 5,
      minParticipants: 2,
      maxParticipants: 4,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.flexibility, AbilityType.agility, AbilityType.cooperation],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['大人が崩れ落ちて子どもを潰さないよう、しっかり体勢を維持しましょう。'],
      steps: ['大人が四つん足でトンネルを作ります。', '子どもは「しゅっぱーつ！」とトンネルを潜り抜けます。', 'トンネルの高さを低くして難易度チェンジ。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「腹ばいでスルスル進むのがすっごく速い！」', '「体が柔らかくて狭いトンネルも余裕だったね！」'],
    ),

    // 39
    Activity(
      id: 'act_039',
      title: '後ろ歩き・横歩きサイドステップラリー',
      description: '普段使わない筋肉を刺激！後ろ向き歩きやカニさん横歩きで決められたコースを進みます。',
      minAge: 5,
      maxAge: 10,
      minParticipants: 2,
      maxParticipants: 4,
      durationMinutes: 15,
      locationTypes: [LocationType.park, LocationType.yard],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.balance, AbilityType.agility, AbilityType.rhythm],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['後ろ歩きの際は転倒しないよう後ろを時々振り返りながら行いましょう。'],
      steps: ['直線のコースを設定します。', '行きはサイドステップ（カニ歩き）、帰りはバックステップ。', '足を交差させずにスムーズに移動する練習です。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「サイドステップのリズムがとても軽やか！」', '「足腰のバランス感覚がしっかり育ってるね！」'],
    ),

    // 40
    Activity(
      id: 'act_040',
      title: '水鉄砲ターゲットスナイパー',
      description: 'ペットボトルや紙でつくった的に水鉄砲で狙い撃ち！夏場のお庭や公園で大活躍。',
      minAge: 4,
      maxAge: 10,
      minParticipants: 1,
      maxParticipants: 5,
      durationMinutes: 20,
      locationTypes: [LocationType.yard, LocationType.park],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.thinking, AbilityType.agility, AbilityType.stamina],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['人の目や顔に直接水を噴射しないよう安全ルールを約束してください。'],
      steps: ['ペットボトルに紙のポスターを貼り付けて的にします。', '一定の距離から水鉄砲を噴射！', '紙が濡れて破けたらターゲット撃破！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「集中して的の真ん中を狙えてスナイパーみたい！」', '「水の残量を計算しながら上手に使えたね！」'],
      seasons: [Season.summer], // 夏限定！
    ),

    // 41
    Activity(
      id: 'act_041',
      title: '缶踏み・空き缶キックターゲット',
      description: '空き缶やプラスチックコーンを的にして、サッカーのように足でボールを当てて倒す！',
      minAge: 7,
      maxAge: 12,
      minParticipants: 2,
      maxParticipants: 5,
      durationMinutes: 20,
      locationTypes: [LocationType.park, LocationType.spacious],
      toolsRequired: ['ボール', 'マーカー/コーン'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.stamina, AbilityType.thinking, AbilityType.agility],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['缶の切り口でケガをしないよう安全なプラスチックコーンや潰した缶を使ってください。'],
      steps: ['10メートル先に目標のコーンを置きます。', 'インサイドキックで正確に狙いを定めてキック！', '倒した回数を競います。'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「インサイドキックの面が綺麗にボールに当たってる！」', '「狙い通りのコースにボールが飛んで見事ヒット！」'],
    ),

    // 42
    Activity(
      id: 'act_042',
      title: 'フローリングバスタオルそりレース',
      description: 'バスタオルの上に子どもが座り、親がタオルを引っ張って室内を滑走するワクワク乗物ゲーム！',
      minAge: 2,
      maxAge: 5,
      minParticipants: 2,
      maxParticipants: 3,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['タオル'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.balance, AbilityType.cooperation, AbilityType.stamina],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 4,
      safetyTips: ['曲がり角で振られて壁にぶつからないよう速度を調整してください。'],
      steps: ['バスタオルを床に広げ、子どもが中央に体操座りします。', 'タオル端を大人が持って安全なスピードで引っ張ります。', '「出発進行〜！」でリビングを爽快サーキット。'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「手でタオルをしっかり握って振り落とされなかったね！」', '「楽しそうな笑顔で乗っていてパパ/ママも嬉しい！」'],
    ),

    // 43
    Activity(
      id: 'act_043',
      title: '音楽に合わせてフリーズダンス',
      description: '好きな曲を流してノリノリでダンス！音楽が止まった瞬間に石のようにカチコチ静止。',
      minAge: 3,
      maxAge: 9,
      minParticipants: 1,
      maxParticipants: 6,
      durationMinutes: 15,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.rhythm, AbilityType.balance, AbilityType.agility],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['跳ねて足を痛めないよう靴下を脱ぐかマットの上で行ってください。'],
      steps: ['音楽を再生して自由に体を動かします。', '親がランダムに音楽を一時停止！', 'ポーズをそのままキープ。動いてしまったらアウト！'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「音楽が止まった瞬間のピタッと静止が見事！」', '「オリジナルのダンスポーズがすごく創造的！」'],
    ),

    // 44
    Activity(
      id: 'act_044',
      title: '部屋いっぱいのくもの巣脱出ゲーム',
      description: '廊下や部屋に毛糸やテープを張り巡らせ、「くもの巣」に触れないように潜り抜けて脱出！',
      minAge: 4,
      maxAge: 9,
      minParticipants: 1,
      maxParticipants: 4,
      durationMinutes: 20,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.flexibility, AbilityType.thinking, AbilityType.balance],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['糸に足を引っかけた際に転倒しないよう柔らかい毛糸を使用してください。'],
      steps: ['廊下の壁や椅子に毛糸を張り巡らせます。', '糸に身体や服が触れないようにまたいだり潜ったりします。', '無事にゴールまでたどり着ければ脱出成功！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「身体を柔軟にしなやかに折り曲げててすごい！」', '「どの隙間を通るか慎重に考えて進めたね！」'],
    ),

    // 45
    Activity(
      id: 'act_045',
      title: 'ミニサッカーPKシュート対決',
      description: 'コーンで作ったミニゴールへ狙い澄ましてPKシュート！キーパーとの心理戦とキック精度向上。',
      minAge: 4,
      maxAge: 11,
      minParticipants: 2,
      maxParticipants: 5,
      durationMinutes: 20,
      locationTypes: [LocationType.park, LocationType.yard, LocationType.spacious],
      toolsRequired: ['ボール', 'マーカー/コーン'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.stamina, AbilityType.thinking, AbilityType.agility],
      isRainOk: false,
      isIndoorOk: false,
      safetyLevel: 5,
      safetyTips: ['強いボールが顔に当たらないよう柔らかいサッカーボールを使いましょう。'],
      steps: ['コーンを2個置いて幅2mのゴールを作ります。', 'キッカーとキーパーに分かれてPK戦！', '5本中何本ゴールを決められるか勝負。'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「キーパーの動きの逆をつくナイスシュート！」', '「コースをしっかり狙えて隅っこに決まったね！」'],
    ),

    // 46
    Activity(
      id: 'act_046',
      title: 'スローモーション走るレース',
      description: '全身を大げさに使って、超スローモーションで走る対決！筋肉のコントロールと爆笑を誘います。',
      minAge: 4,
      maxAge: 10,
      minParticipants: 2,
      maxParticipants: 5,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor, LocationType.yard, LocationType.park],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.balance, AbilityType.flexibility, AbilityType.thinking],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['片足立ちの姿勢が長くなるためよろけないよう注意してください。'],
      steps: ['スタートラインに立ちます。', '「映画のスローモーションみたいに走るよ！」でスタート。', '一番ゆっくりゴールした人が勝ち！'],
      parentInvolvement: ParentInvolvementLevel.active,
      parentPraiseTips: ['「腕の振りと脚の持ち上げが本物のスローモーション映像みたい！」', '「途中で止まらずにゆっくり動き続けられたね！」'],
    ),

    // 47
    Activity(
      id: 'act_047',
      title: 'バランスボールぽんぽん乗馬',
      description: 'バランスボールの上に座ってぽんぽん弾んだり、両足を浮かせて体幹キープにチャレンジ！',
      minAge: 4,
      maxAge: 10,
      minParticipants: 1,
      maxParticipants: 3,
      durationMinutes: 15,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['ボール'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.balance, AbilityType.stamina, AbilityType.rhythm],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 4,
      safetyTips: ['後ろに転倒しないよう大人がすぐ後ろで手を添えていてください。'],
      steps: ['バランスボールに深く腰掛けます。', '大人が手を繋ぎながらリズムよく上下にポンポン跳ねます。', '両手を離して10秒キープできるかチャレンジ。'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「背筋がピーンと伸びてバランスボールに上手乗れてる！」', '「お腹の力でしっかり姿勢を支えられてるね！」'],
    ),

    // 48
    Activity(
      id: 'act_048',
      title: '階段ぽんぽんステップ運動',
      description: '階段の1段目を使って、登って降りてのリズミカルなステップ昇降！脚力と持久力を高めます。',
      minAge: 6,
      maxAge: 12,
      minParticipants: 1,
      maxParticipants: 2,
      durationMinutes: 10,
      locationTypes: [LocationType.indoor],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.high,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.stamina, AbilityType.rhythm, AbilityType.agility],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 4,
      safetyTips: ['手すりを掴める位置で行い、最下段の1段目のみを使用してください。'],
      steps: ['階段の1段目の前に立ちます。', '右足→左足で登り、右足→左足で降ります。', '「トントン・トントン」とテンポよく1分間継続。'],
      parentInvolvement: ParentInvolvementLevel.watching,
      parentPraiseTips: ['「足元のステップがリズムよく軽やかだね！」', '「息を弾ませながら最後までやりきったタフさがすごい！」'],
    ),

    // 49
    Activity(
      id: 'act_049',
      title: 'ペットボトルボウリング',
      description: '水を入れたペットボトルピンにボールを転がしてストライクを狙うエコで楽しい定番ボウリング！',
      minAge: 3,
      maxAge: 8,
      minParticipants: 1,
      maxParticipants: 4,
      durationMinutes: 20,
      locationTypes: [LocationType.indoor, LocationType.yard],
      toolsRequired: ['ボール'],
      intensityLevel: IntensityLevel.low,
      difficultyLevel: DifficultyLevel.easy,
      trainableAbilities: [AbilityType.thinking, AbilityType.agility, AbilityType.rhythm],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['ペットボトルが倒れて水が漏れないようキャップを固く閉めてください。'],
      steps: ['ペットボトル6本に少し水を入れて並べます。', '離れた場所から球を転がします。', '2回投げて何本倒せるかスコアカードに記録！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「狙いすましたストライク！ガッツポーズがカッコいい！」', '「ボールをまっすぐ転がす手首の使い方が完璧！」'],
    ),

    // 50
    Activity(
      id: 'act_050',
      title: 'チーム連携フラフープくぐり',
      description: 'みんなで手をつないだまま、手を離さずにフラフープを体に潜らせて隣の人へ送り届けるリレー！',
      minAge: 5,
      maxAge: 12,
      minParticipants: 3,
      maxParticipants: 8,
      durationMinutes: 15,
      locationTypes: [LocationType.indoor, LocationType.park, LocationType.spacious],
      toolsRequired: ['なし（道具不要）'],
      intensityLevel: IntensityLevel.medium,
      difficultyLevel: DifficultyLevel.normal,
      trainableAbilities: [AbilityType.cooperation, AbilityType.flexibility, AbilityType.thinking],
      isRainOk: true,
      isIndoorOk: true,
      safetyLevel: 5,
      safetyTips: ['手をつないで引っ張りすぎないよう注意しましょう。'],
      steps: ['全員で輪になって手をつなぎます。', 'フラフープを肩や頭、足に潜らせて隣の人へ送ります。', '手を一度も離さずに何秒で1周できるかチームでチャレンジ！'],
      parentInvolvement: ParentInvolvementLevel.moderate,
      parentPraiseTips: ['「知恵を出し合って体をしなやかに通せたね！」', '「声を掛け合ってチームワークバッチリ！」'],
    ),
  ];

  @override
  Future<List<Activity>> getAllActivities() async {
    if (_cachedActivities != null && _cachedActivities!.isNotEmpty) {
      return _cachedActivities!;
    }

    try {
      final csvString = await rootBundle.loadString('assets/data/activities.csv');
      // BOMヘッダー除去
      final cleanCsv = csvString.startsWith('\uFEFF')
          ? csvString.substring(1)
          : csvString;

      final rows = const CsvToListConverter().convert(cleanCsv);
      if (rows.length > 1) {
        final list = <Activity>[];
        for (int i = 1; i < rows.length; i++) {
          final row = rows[i];
          if (row.isEmpty || row[0].toString().trim().isEmpty) continue;
          list.add(Activity.fromCsvRow(row));
        }
        if (list.isNotEmpty) {
          _cachedActivities = list;
          return list;
        }
      }
    } catch (_) {
      // ロード失敗時や環境未対応時はフォールバック
    }

    _cachedActivities = _seedActivities;
    return _seedActivities;
  }

  @override
  Future<Activity?> getActivityById(String id) async {
    final all = await getAllActivities();
    try {
      return all.firstWhere((a) => a.id == id);
    } catch (_) {
      return null;
    }
  }
}

/// Provider定義
final activityRepositoryProvider = Provider<ActivityRepository>((ref) {
  return FirestoreActivityRepository();
});
